version: '3'
services:
  chat-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: sh -c "cd ./chat-tool; npm start"
