version: '3'
services:
  front:
    build: ./
    container_name: node
    volumes:
      - ./chat:/chat
    working_dir: /chat
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: sh -c "cd ./chat; npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
